# Generated by Django 3.2 on 2021-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0023_auto_20210726_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='estadoCivil',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='gener',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='estatus',
            field=models.CharField(choices=[('f', 'Usuario destacado'), ('c', 'Creador de contenido'), ('u', 'Usuario nuevo')], default='u', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='genero',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='rol',
            field=models.CharField(choices=[('a', 'Administrador'), ('u', 'Usuario'), ('e', 'Especialista')], default='u', max_length=1, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='url_facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='url_instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='url_twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='perfiles',
            name='url_website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Web Site'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto de perfil'),
        ),
    ]
