# Generated by Django 3.2 on 2021-08-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0024_auto_20210731_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios_articulo',
            name='usuario',
        ),
    ]
